### ISSUE TITLE
Error from Visual Studio

### ISSUE THREAD

**Issue by Essxnce** [aboulch/ConvPoint#10]
Hello,
When I tried to operate setup.py, I got the error like below:

-

(base) C:\Users\plati\Desktop\ConvPoint\examples\semantic3d\semantic3D_utils>python setup.py install --home="."
running install
running build
running build_ext
skipping 'Semantic3D.cpp' Cython extension (up-to-date)
building 'semantic3D' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -I./ -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /TpSemantic3D.cpp /Fobuild\temp.win-amd64-3.7\Release\Semantic3D.obj -std=c++11 -fopenmp
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
Semantic3D.cpp
Semantic3D.cpp(607): fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

-

and I don't know why..How can I fix this?

**Comment by aboulch** [comment]
Hello,
The code was tested on Ubuntu 16.04 / 18.04. As I do not work on Windows, I cannot say how to fix this bug. I am not familiar with visual studio.
The error seems to be related to missing numpy includes, I do not now how to look for them with VS.

**Comment by Essxnce** [comment]
Oh, I'm not using VS, but the error message said about VS, so I used the word.
I'm using anaconda prompt in Windows 10.
I solved the problem by copying numpy directory from C:\ProgramData\Anaconda3\Lib\site-packages\numpy\core\include to C:\ProgramData\Anaconda3\include.

But I'm stuck with another problem, the error message is like that (I omited some lines because it is too long, ):

-
(base) D:\TOMB\ConvPoint\examples\semantic3d>python semantic3d_seg.py --rootdir path_to_data_processed --savedir path_to_save_dir
Creating the network...Model with dropout
Done
Create the datasets...Done
Create optimizer...Done
Epoch 0:   0%|                                                              | 0/100 [00:00<?, ?it/s]tensor([    0,  8192, 16384, 24576, 32768, 40960, 49152, 57344],
       device='cuda:0')
C:/w/1/s/tmp_conda_3.7_055306/conda/conda-bld/pytorch_1556690124416/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: block: [25,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

...

C:/w/1/s/tmp_conda_3.7_055306/conda/conda-bld/pytorch_1556690124416/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: block: [25,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

...

C:/w/1/s/tmp_conda_3.7_055306/conda/conda-bld/pytorch_1556690124416/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: block: [25,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/w/1/s/tmp_conda_3.7_055306/conda/conda-bld/pytorch_1556690124416/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: block: [25,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` 

...

C:/w/1/s/tmp_conda_3.7_055306/conda/conda-bld/pytorch_1556690124416/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: block: [34,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "semantic3d_seg.py", line 424, in <module>
    main()
  File "semantic3d_seg.py", line 341, in main
    outputs = net(features, pts)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../..\networks\network_seg.py", line 159, in forward
    x0, _ = self.cv0(x, input_pts, 16)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../..\convpoint\nn\conv.py", line 89, in forward
    maxi[maxi==0] = 1
RuntimeError: copy_if failed to synchronize: device-side assert triggered

**Comment by Essxnce** [comment]
and for figuring out the problem, I run semantic3d_seg.py without CUDA, and the error message is like this:

-

(base) D:\TOMB\ConvPoint\examples\semantic3d>python semantic3d_seg.py --rootdir path_to_data_processed --savedir path_to_save_dir
Creating the network...Model with dropout
Done
Create the datasets...Done
Create optimizer...Done
Epoch 0:   0%|                                                             | 0/1000 [00:00<?, ?it/s]tensor([     0,   8192,  16384,  24576,  32768,  40960,  49152,  57344,  65536,
         73728,  81920,  90112,  98304, 106496, 114688, 122880])
Traceback (most recent call last):
  File "semantic3d_seg.py", line 424, in <module>
    main()
  File "semantic3d_seg.py", line 341, in main
    outputs = net(features, pts)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../..\networks\network_seg.py", line 159, in forward
    x0, _ = self.cv0(x, input_pts, 16)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../..\convpoint\nn\conv.py", line 79, in forward
    features = input.view(-1, input.size(2))[indices]
IndexError: index 21414706937856 is out of bounds for dimension 0 with size 131072

-

The environment about GPU computing is
GPU: NVIDIA GeForce GTX 1060 3GB
CUDA: 9.0
cuDNN: 7.5.0

**Comment by aboulch** [comment]
Hello,
Can you print `x` and `input_pts` sizes with `print(x.size(), input_pts.size())` ?
By the way I made an update 4 days ago, do you have the up-to-date repo ?

**Comment by aboulch** [comment]
Hello,
Closing the issue: no recent activity.
