### ISSUE TITLE
Index out of Bound error at Epoch 0

### ISSUE THREAD

**Issue by Sajjadmanal** [aboulch/ConvPoint#13]
Hi,

I tried with the below command for npm3d training:

`python npm3d_seg.py --rootdir processeddata/ --savedir savedmodel/`

and it gives me the below mentioned error at epoch 0:

```
Create filelist...done, 86 train files, 3 test files
Creating the network...Model with dropout
Done
Create the datasets...Done
Create optimizer...Done
Epoch 0:   0%|                                                             | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "npm3d_seg.py", line 385, in <module>
    main()
  File "npm3d_seg.py", line 304, in main
    outputs = net(features, pts)
  File "C:\Users\sm50014\AppData\Local\Continuum\anaconda3\envs\lidar\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "../..\networks\network_seg.py", line 159, in forward
    x0, _ = self.cv0(x, input_pts, 16)
  File "C:\Users\sm50014\AppData\Local\Continuum\anaconda3\envs\lidar\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "../..\convpoint\nn\conv.py", line 78, in forward
    features = input.view(-1, input.size(2))[indices]
RuntimeError: index 35180077186177 is out of bounds for dimension 0 with size 131072
```

**Comment by aboulch** [comment]
Hello,
Sorry for this late response.
Did you solve the problem ?
