### ISSUE TITLE
I'm sorry to disturb you.Problems that arise when I run your Codes.  I use Python 3.7, and pytorch1.1.0.Thank you again!.

### ISSUE THREAD

**Issue by Xjunjiang** [aboulch/ConvPoint#2]
Creating network
Number of parameters 962558
Getting train files...
(9840, 2048, 3) (9840, 1)
Getting test files...
(2468, 2048, 3) (2468, 1)
done
Creating dataloaders...done
Epoch 0:   0%|                                                                                            | 0/615 [00:00<?, ?it/s]Traceback (most recent call last):
  File "modelnet_classif.py", line 313, in <module>
    main()
  File "modelnet_classif.py", line 235, in main
    train_aloss, train_oa, train_aa, train_aiou = apply(epoch, training=True)
  File "modelnet_classif.py", line 202, in apply
    outputs = net(features, pts, tree)
  File "/home/xjunjiang/anaconda3/envs/CondaProjects/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xjunjiang/CondaProjects/ConvPoint/network_classif.py", line 56, in forward
    x2 = conv(x1, self.cv2, tree, layer_id, self.bn2)
  File "/home/xjunjiang/CondaProjects/ConvPoint/network_classif.py", line 11, in conv
    x = layer(x, tree[layer_id]["points"], tree[layer_id+1]["indices"])
  File "/home/xjunjiang/anaconda3/envs/CondaProjects/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xjunjiang/CondaProjects/ConvPoint/layers/conv.py", line 79, in forward
    features = torch.matmul(features, self.weight)
RuntimeError: The size of tensor a (16) must match the size of tensor b (64) at non-singleton dimension 0

**Comment by aboulch** [comment]
Hello,
I fixed the bug: a reshape step on the weights was missing.
Tell me if it works.

**Comment by Xjunjiang** [comment]
It works well,thank you ! @aboulch
