### ISSUE TITLE
IndexError: too many indices for array in seamntic3d_seg.py

### ISSUE THREAD

**Issue by Jonathan-Cotugno** [aboulch/ConvPoint#21]
Hello! Thanks for publicly releasing the code! I'm trying to run the network on the semantic 3d dataset. I've run the prepare_data.py file already, but when I go to run semantic3d_seg.py, I keep getting an indexerror. Seems to occur when iterating through the train_loader.

Here is the output:

> Creating the network...Model with dropout
Done
Create the datasets...Done
Create optimizer...Done
Epoch 0:   0%|                                                             | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "semantic3d_seg.py", line 421, in <module>
    main()
  File "semantic3d_seg.py", line 331, in main
    for pts, features, seg in t:
  File "/home/jonathan/anaconda3/envs/convpoint/lib/python3.7/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/jonathan/anaconda3/envs/convpoint/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/jonathan/anaconda3/envs/convpoint/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/jonathan/anaconda3/envs/convpoint/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/jonathan/anaconda3/envs/convpoint/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jonathan/anaconda3/envs/convpoint/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jonathan/anaconda3/envs/convpoint/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jonathan/anaconda3/envs/convpoint/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "semantic3d_seg.py", line 103, in __getitem__
    fts = pts[:,3:6]
IndexError: too many indices for array

Any help would be great! Thanks :)

**Comment by aboulch** [comment]
Hello,
Sorry for late response.
I cannot reproduce the error.
* Please check the size of the generated npy files using prepare_data.py. If the size is very small, the script did not find the original semantic 3D files.
* Maybe add a `print(pts.shape)` at line 102. It shall be something like [number_of_points, 7], each line would be x,y,z,r,g,b,label (for training data)

**Comment by Jonathan-Cotugno** [comment]
yes sorry there was a misnamed file when downloading from semantic 3D that I didnt catch.
