### ISSUE TITLE
IndexError: index 687194800128 is out of bounds for dimension 0 with size 131072

### ISSUE THREAD

**Issue by mgveliko** [aboulch/ConvPoint#39]
Hello, 

First, thanks for sharing your code, it is really helpful to have it along with reading the paper. Great work!

I have tried running the code for the npm3d both with the original datasets and by creating a custom data set. 
In both cases, I receive the following error: IndexError: index 687194800128 is out of bounds for dimension 0 with size 131072, where each time the index is some random huge number. 

Here is the whole error log when I run npm3d_seg.py  file with  python npm3d_seg.py --rootdir Project_points\processed --savedir Project_points\processed --nocolor

Create filelist...done, 22 train files, 1 test files
Creating the network...Model with dropout
Done
Create the datasets...Done
Create optimizer...Done
Epoch 0:   0%|                                                             | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
 File "C:\Users\mgveliko\Desktop\Project_deep_learning\Project_points\ConvPoint-master\examples\npm3d\npm3d_seg1.py", line 382, in <module>
    main()
  File "C:\Users\mgveliko\Desktop\Project_deep_learning\Project_points\ConvPoint-master\examples\npm3d\npm3d_seg1.py", line 301, in main
    outputs = net(features, pts)
  File "C:\Users\mgveliko\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\mgveliko\Desktop\Project_deep_learning\Project_points\ConvPoint-master\networks\network_seg.py", line 159, in forward
    x0, _ = self.cv0(x, input_pts, 16)
  File "C:\Users\mgveliko\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\mgveliko\Desktop\Project_deep_learning\Project_points\ConvPoint-master\convpoint\nn\conv.py", line 78, in forward
    features = input.view(-1, input.size(2))[indices]
**IndexError: index 687194800128 is out of bounds for dimension 0 with size 131072**

Here I use only part of the NPM3D example files, and I receive the very same error if I use my own custom data set that has the same structure as the NPM3D files.

Any idea about the error?

**Comment by mgveliko** [comment]
Solved. 
I was trying to run the code under Windows, and it was throwing this weird error.
Run it under Linux and no error message, code runs and produces results. 
Might be an issue with the nearest neighbors library as there was an open issue that it does not run correctly under windows.
Thanks again for the code!

**Comment by xiehou-design** [comment]
Did you run it successfully in Windows 10? I have the same problem.
